export const filterData = [
  { name: "Lunch", Image: require("../../assets/image3.jpg"), id: "0" },
  { name: "Snacks", Image: require("../../assets/image5.jpg"), id: "1" },
  { name: "Dinner", Image: require("../../assets/image2.jpg"), id: "2" },
  { name: "Sweets", Image: require("../../assets/image6.jpg"), id: "3" },
  { name: "Sweets", Image: require("../../assets/image7.jpg"), id: "4" },
  { name: "Authentic", Image: require("../../assets/image8.jpg"), id: "5" },
];

export const ChefData = [
  {
    ChefName: "Maya Shrestha",
    farAway: "21.2",
    kitchenAddress: "Suncity Apartment",
    images: require("../../assets/image3.jpg"),
    averageReview: 4.9,
    numberOfReview: 52,
    coordinates: { lat: -26.1888612, lng: 28.246325 },
    discount: 10,
    deliveryTime: 15,
    collectTime: 5,
    foodType: "Daalbhat set,Newari set,Roti tarkari",
    productData: [
      {
        name: "Daalbhat set",
        price: 120,
        images: require("../../assets/image2.jpg"),
      },
      {
        name: "Newari set",
        price: 170,
        images: require("../../assets/image11.jpg"),
      },
      {
        name: "Roti tarkari",
        price: 80,
        images: require("../../assets/image12.jpeg"),
      },
    ],
    id: 0,
  },

  {
    ChefName: "Maya Shrestha",
    farAway: "21.2",
    kitchenAddress: "Suncity Apartment",
    images: require("../../assets/image3.jpg"),
    averageReview: 4.9,
    numberOfReview: 52,
    coordinates: { lat: -26.1888612, lng: 28.246325 },
    discount: 10,
    deliveryTime: 15,
    collectTime: 5,
    foodType: "Daalbhat set,Newari set,Roti tarkari",
    productData: [
      {
        name: "Daalbhat set",
        price: 120,
        Image: require("../../assets/image2.jpg"),
      },
      {
        name: "Newari set",
        price: 170,
        Image: require("../../assets/image11.jpg"),
      },
      {
        name: "Roti tarkari",
        price: 80,
        Image: require("../../assets/image12.jpeg"),
      },
    ],
    id: 1,
  },

  {
    ChefName: "Maya Shrestha",
    farAway: "21.2",
    kitchenAddress: "Suncity Apartment",
    images: require("../../assets/image3.jpg"),
    averageReview: 4.9,
    numberOfReview: 52,
    coordinates: { lat: -26.1888612, lng: 28.246325 },
    discount: 10,
    deliveryTime: 15,
    collectTime: 5,
    foodType: "Daalbhat set,Newari set,Roti tarkari",
    productData: [
      {
        name: "Daalbhat set",
        price: 120,
        Image: require("../../assets/image2.jpg"),
      },
      {
        name: "Newari set",
        price: 170,
        Image: require("../../assets/image11.jpg"),
      },
      {
        name: "Roti tarkari",
        price: 80,
        Image: require("../../assets/image12.jpeg"),
      },
    ],
    id: 2,
  },

  {
    ChefName: "Maya Shrestha",
    farAway: "21.2",
    kitchenAddress: "Suncity Apartment",
    images: require("../../assets/image3.jpg"),
    averageReview: 4.9,
    numberOfReview: 52,
    coordinates: { lat: -26.1888612, lng: 28.246325 },
    discount: 10,
    deliveryTime: 15,
    collectTime: 5,
    foodType: "Daalbhat set,Newari set,Roti tarkari",
    productData: [
      {
        name: "Daalbhat set",
        price: 120,
        Image: require("../../assets/image2.jpg"),
      },
      {
        name: "Newari set",
        price: 170,
        Image: require("../../assets/image11.jpg"),
      },
      {
        name: "Roti tarkari",
        price: 80,
        Image: require("../../assets/image12.jpeg"),
      },
    ],
    id: 3,
  },
];

export const foodData = [
  {
    name: "Daal bhaat tarkari",
    price: 170,
    Image: require("../../assets/image2.jpg"),
    id: 0,
  },
  {
    name: "Mixed set",
    price: 170,
    Image: require("../../assets/image3.jpg"),
    id: 1,
  },
  {
    name: "Roti tarkari",
    price: 80,
    Image: require("../../assets/image12.jpeg"),
    id: 2,
  },
  {
    name: "Diet friendly",
    price: 170,
    Image: require("../../assets/image7.jpg"),
    id: 3,
  },
];
export const specialfoodData = [
  {
    name: "Yomari 2 pieces",
    price: 170,
    Image: require("../../assets/image8.jpg"),
    id: 0,
  },
  {
    name: "Newari set",
    price: 170,
    Image: require("../../assets/image11.jpg"),
    id: 1,
  },
  {
    name: "Newari set",
    price: 170,
    Image: require("../../assets/image11.jpg"),
    id: 2,
  },
  {
    name: "Roti tarkari",
    price: 80,
    Image: require("../../assets/image12.jpeg"),
    id: 3,
  },
  {
    name: "Roti tarkari",
    price: 80,
    Image: require("../../assets/image12.jpeg"),
    id: 4,
  },
];

export const category = ["Everyday", "Today's Special", "My review"];
specialfoodData;

export const Pending = [{
  id: 0,
  chefDistance: "1",
  chefName:"Maya Shrestha",
  customerDistance: "3",
  pickUpPoint: "Gwarko, Lalitpur",
  deliveryPoint: "Jawalakhel, Lalitpur",
  noOfDaysToDeliver: "6",
  rate:600,
},
{
  id: 1,
  chefDistance: "1",
  chefName:"Maya Shrestha",
  customerDistance: "3",
  pickUpPoint: "Gwarko, Lalitpur",
  deliveryPoint: "Jawalakhel, Lalitpur",
  noOfDaysToDeliver: "6",
  rate:600,
},
{
  id: 2,
  chefDistance: "1",
  chefName:"Maya Shrestha",
  customerDistance: "3",
  pickUpPoint: "Gwarko, Lalitpur",
  deliveryPoint: "Jawalakhel, Lalitpur",
  noOfDaysToDeliver: "6",
  rate:600,
},
{
  id: 3,
  chefDistance: "1",
  chefName:"Maya Shrestha",
  customerDistance: "3",
  pickUpPoint: "Gwarko, Lalitpur",
  deliveryPoint: "Jawalakhel, Lalitpur",
  noOfDaysToDeliver: "6",
  rate:600,
},

  {
    id: 6,
    chefDistance: "1",
    chefName:"Maya Shrestha",
    customerDistance: "3",
    pickUpPoint: "Gwarko, Lalitpur",
    deliveryPoint: "Jawalakhel, Lalitpur",
    noOfDaysToDeliver: "6",
    rate:600,
  },
  {
    id: 7,
    chefDistance: "1",
    chefName:"Maya Shrestha",
    customerDistance: "3",
    pickUpPoint: "Gwarko, Lalitpur",
    deliveryPoint: "Jawalakhel, Lalitpur",
    noOfDaysToDeliver: "6",
    rate:600,
  },
  {
    id: 8,
    chefDistance: "1",
    chefName:"Maya Shrestha",
    customerDistance: "3",
    pickUpPoint: "Gwarko, Lalitpur",
    deliveryPoint: "Jawalakhel, Lalitpur",
    noOfDaysToDeliver: "6",
    rate:600,
  },
  {
    id: 9,
    chefDistance: "1",
    chefName:"Maya Shrestha",
    customerDistance: "3",
    pickUpPoint: "Gwarko, Lalitpur",
    deliveryPoint: "Jawalakhel, Lalitpur",
    noOfDaysToDeliver: "6",
    rate:600,
  },
  {
    id: 10,
    chefDistance: "1",
    chefName:"Maya Shrestha",
    customerDistance: "3",
    pickUpPoint: "Gwarko, Lalitpur",
    deliveryPoint: "Jawalakhel, Lalitpur",
    noOfDaysToDeliver: "6",
    rate:600,
  },
  {
    id: 11,
    chefDistance: "1",
    chefName:"Maya Shrestha",
    customerDistance: "3",
    pickUpPoint: "Gwarko, Lalitpur",
    deliveryPoint: "Jawalakhel, Lalitpur",
    noOfDaysToDeliver: "6",
    rate:600,
  },
  {
  id:12,
  chefDistance:"5",
  chefName:"Maya Shrestha",
  customerDistance: "3",
  pickUpPoint: "Gwarko, Lalitpur",
  deliveryPoint: "Jawalakhel, Lalitpur",
  noOfDaysToDeliver: "6",
  rate:600,
},
{
  id: 12,
  chefDistance: "1",
  chefName:"Maya Shrestha",
  customerDistance: "3",
  pickUpPoint: "Gwarko, Lalitpur",
  deliveryPoint: "Jawalakhel, Lalitpur",
  noOfDaysToDeliver: "6",
  rate:600,
},

];
export const Accepted = [{
  id: 0,
  chefDistance: "1",
  chefName:"Maya Shrestha",
  customerDistance: "3",
  pickUpPoint: "Gwarko, Lalitpur",
  deliveryPoint: "Jawalakhel, Lalitpur",
  noOfDaysToDeliver: "6",
  rate:600,
},
{
  id: 1,
  chefDistance: "1",
  chefName:"Maya Shrestha",
  customerDistance: "3",
  pickUpPoint: "Gwarko, Lalitpur",
  deliveryPoint: "Jawalakhel, Lalitpur",
  noOfDaysToDeliver: "6",
  rate:600,
},
{
  id: 2,
  chefDistance: "1",
  chefName:"Maya Shrestha",
  customerDistance: "3",
  pickUpPoint: "Gwarko, Lalitpur",
  deliveryPoint: "Jawalakhel, Lalitpur",
  noOfDaysToDeliver: "6",
  rate:600,
},
{
  id: 3,
  chefDistance: "1",
  chefName:"Maya Shrestha",
  customerDistance: "3",
  pickUpPoint: "Gwarko, Lalitpur",
  deliveryPoint: "Jawalakhel, Lalitpur",
  noOfDaysToDeliver: "6",
  rate:600,
},
{
  id: 4,
  chefDistance: "1",
  chefName:"Maya Shrestha",
  customerDistance: "3",
  pickUpPoint: "Gwarko, Lalitpur",
  deliveryPoint: "Jawalakhel, Lalitpur",
  noOfDaysToDeliver: "6",
  rate:600,
},
{
  id: 5,
  chefDistance: "1",
  chefName:"Maya Shrestha",
  customerDistance: "3",
  pickUpPoint: "Gwarko, Lalitpur",
  deliveryPoint: "Jawalakhel, Lalitpur",
  noOfDaysToDeliver: "6",
  rate:600,
},
];

export const Subscriber = [{
  id: 0,
  customerName:"Aayusha Shrestha",
  customerDistance: "3",
  deliveryPoint: "Jawalakhel, Lalitpur",
  noOfDaysToDeliver: "6",
  deliveryTime: "9:30am",
  rate:600,
},
{
  id: 1,
  customerName:"Aayusha Shrestha",
  customerDistance: "3",
  deliveryPoint: "Jawalakhel, Lalitpur",
  noOfDaysToDeliver: "6",
  deliveryTime: "9:30am",
  rate:600,
},
{
  id: 0,
  customerName:"Aayusha Shrestha",
  customerDistance: "3",
  deliveryPoint: "Jawalakhel, Lalitpur",
  noOfDaysToDeliver: "6",
  deliveryTime: "9:30am",
  rate:600,
},
{
  id: 0,
  customerName:"Aayusha Shrestha",
  customerDistance: "3",
  deliveryPoint: "Jawalakhel, Lalitpur",
  noOfDaysToDeliver: "6",
  deliveryTime: "9:30am",
  rate:600,
},
{
  id: 0,
  customerName:"Aayusha Shrestha",
  customerDistance: "3",
  deliveryPoint: "Jawalakhel, Lalitpur",
  noOfDaysToDeliver: "6",
  deliveryTime: "9:30am",
  orderName:"Mixed Set",
  rate:600,
},
]